--- # Variables command line passing example
- hosts: '{{ hosts }}'
  user: '{{ user }}'
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: install soem software
      yum: pkg={{ pkg }} state=latest
