--- # mount exampel
- hosts: all
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: mount the remote data patition
      mount: name=/mnt/data src=/dev=xvdf1 fstype=ext3 opts=rw state=present
