--- # RUNONCE playbook Example
- hosts: all
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Run the uptime command on all hosts and log it
      raw: /usr/bin/uptime >> /home/test/uptime.log
    - name: List the /var directory and log it
      raw: ls -al /var >> /home/test/dir.list
      run_once: true  // run one time on the first server of the all  specifiyed above 
